### ISSUE TITLE
Exporting the trained model

### ISSUE THREAD

**Issue by alexbudin** [googlecreativelab/teachable-machine-v1#37]
Hi guys,

You have said you are releasing a more awesome teachable machine tool: https://teachablemachine.withgoogle.com/io19 and i can't wait to see that.

I have emailed to get access to a BETA version, and i hope i do :)  but wanted to know if there is any way of exporting the trained model with the boilerplate at the moment or with this version.

I want to be able to train the system to recognize a specific object, but have no idea how to export the model from the current web tool.

Any help would be greatly appreciated.

Thank you,

Alex

**Comment by hapticdata** [comment]
Hi Alex,
I don't see any emails requesting beta when searching for your name. If you haven't heard back from us please send us another e-mail.

The original Teachable Machine uses a KNN Classifier and is not capable of exporting a trained model. The new Teachable Machine uses transfer learning on top of mobilenet, so while the results are similar the processes are different.

The new Teachable Machine is going public soon and we can't wait to see what you make. In addition to the site we are releasing [support libraries](https://github.com/googlecreativelab/teachablemachine-libraries) and if you put in some extra work you can train and save a model using the image libraries `TeachableMobileNet` class.

**Comment by munna71** [comment]
![Screenshot (124)](https://user-images.githubusercontent.com/63259520/78758360-d3e54380-799f-11ea-9bcd-ab3c2829d684.png)

I can not download quantized model on "tensorflow lite" .It's very urgent and importent for me....
pleace.....tel me the solusion as soon as posible....pleace..............

my email:- shahriarhm007@gmail.com

**Comment by hapticdata** [comment]
this should be working now, also this is the wrong repository for this issue. Please use teachablemachine-community repo instead.
