### ISSUE TITLE
Will you be open sourcing V2?

### ISSUE THREAD

**Issue by 0rvar** [googlecreativelab/teachable-machine-v1#38]
I saw that there is a new version of Teachable Machine with Pose Estimation and other goodies. Will you be open sourcing that too? I see that the Community repository has some related code, but not enough to get clueless people started building forks of Teachable Machine

**Comment by hapticdata** [comment]
The [teachable-community](https://github.com/googlecreativelab/teachablemachine-community) repo will be the best place for these discussions.
At this point we don't have plans to open-source the site's code or UI for Teachable Machine. In the community libraries we do however include the code that relates to transfer learning and training. The classes such as `TeachablePoseNet` make it fairly simple to add data and train your own models.
