### ISSUE TITLE
How to join 2 image models?

### ISSUE THREAD

**Issue by PixsaOJ** [googlecreativelab/teachable-machine-v1#39]
Hi! I was wondering, how can I join 2 trained model data together? e.g my friend wants me to help with training AI to recognize some objects. I know we could take and share photos but is there any other clever way? Maybe joining JSON data?

**Comment by hapticdata** [comment]
hi, I believe this question is intended for this repository? https://github.com/googlecreativelab/teachablemachine-community

Your best bet is to train a new model combining the original datasets, the JSON files won't be of help they just describe the model.

**Comment by PixsaOJ** [comment]
Okay thanks ! I will move this question there.
