### ISSUE TITLE
Image based ML models trained on TeachableMachine V2 show 'NaN' prediction on Chrome and Firefox (Windows OS v 7)

### ISSUE THREAD

**Issue by pmov** [googlecreativelab/teachable-machine-v1#43]
Image based ML models trained on TeachableMachine V2 show 'NaN' prediction on Chrome and Firefox (Windows OS v 7).What could be the problem? The models do not work after training.No errors shown while or after training also.

**Comment by hapticdata** [comment]
hello, the image based models are working as expected. It seems this may be an issue with your particular code. Perhaps you can provide an example of what your setup is like?

**Comment by Aendir** [comment]
Hi, I am facing this same issue, but on a different platform.
I have an Android app, which creates a Chrome Webview. From inside the webview, upon calling `model.predict()`, I keep getting NaN as the probability value for all classes.

When I try this from a website that holds the exact same JavaScript code as the webview, it works perfectly fine.
Additionally, when I try to use TensorflowJS to get the classification of an image using the pretrained mobileNet model, it works fine in both the website and the webview.

But if I attempt to use TensorflowJS and the tensforflow model (attribute within the Teachable Machine Model), to get the classification for a TM Image model, I keep getting "NaN".

Model being Used: https://teachablemachine.withgoogle.com/models/LDsdxzd1H/

System Info:
Device: OnePlus 6
Android 10
Gradle version: 4.0.1
Cordova version: 5.3.0-dev
Chrome: 87.0.4280.101

**Comment by Aendir** [comment]
Hello,
I was able to resolve the issue I was facing.
The problem was that when the model was being loaded, my code was treating the contents of the `weights.bin` file as a string (When loading from from within the webview).
Once I fixed this and treated the contents of `weights.bin` as an arraybuffer, the prediction started working fine.

Hope this helps someone.
