### ISSUE TITLE
A saved model now only picks one category when it worked well about a month ago

### ISSUE THREAD

**Issue by ToonTalk** [googlecreativelab/teachable-machine-v1#45]
This model distinguishes between my left and right hand: https://teachablemachine.withgoogle.com/models/X3b80T2Ho/

It now reports either hand as right and yet it worked a few weeks ago. Both were trained with the same lighting, background etc just a minute apart. Flipping the camera input image has no effect.

I just retrained a model in the same way and this one works fine: https://teachablemachine.withgoogle.com/models/0O5MUcOjY/

Why would the old model stop working?

**Comment by hapticdata** [comment]
hello,
it looks like this is a question about the current Teachable Machine, over here https://github.com/googlecreativelab/teachablemachine-community

The difference likely comes down to things like lighting, clothing you were wearing, angle, perspective, background when comparing how you are inferring / predicting with your model now, compared to when it was trained.
You will likely see your new model have the same issues.

Ultimately this model is making predictions using patterns in pixel colors. If you want to make your model more resilient you will need your training data to be more robust, adding samples from different lighting, clothing, distance from camera etc.
